### ISSUE TITLE
document V.5 migration for "NgxFormly: passing 'FormlyFormBuilder' to ... type is not required anymore, you may remove it!

### ISSUE THREAD

**Issue by htrex** [ngx-formly/ngx-formly#1425]
I've a custom component similar to this:
```
export class FormlyDatatableComponent extends FieldArrayType implements OnInit {
    constructor(
        builder: FormlyFormBuilder,
    ) {
        super(builder);
    }
}
```
after an upgrade from ngx-formly 5.0.0-beta.21 to 5.0.0-rc.1 I'm seeing the message
"NgxFormly: passing 'FormlyFormBuilder' to 'FormlyDatatableComponent' type is not required anymore, you may remove it!"

but removing the injection and the super call gives
"error TS2377: Constructors for derived classes must contain a 'super' call."

could you please document how to correctly refactor the deprecated syntax?

**Comment by aitboudad** [comment]
when you try to override the constructor of an extended class calling `super()` is required.
in your case either remove the constructor entirely or call `super();`  without passing `builder` argument

**Comment by htrex** [comment]
Thanks for the explanation!
