### ISSUE TITLE
After update to 6.0.0-next.8 - Failed to compile.

### ISSUE THREAD

**Issue by adora-tech** [ngx-formly/ngx-formly#3201]
Hello all,

I am using:

```
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/cli": "~13.2.1",

    "@ngx-formly/bootstrap": "^6.0.0-next.8",
    "@ngx-formly/core": "^6.0.0-next.8",
    "@ngx-formly/schematics": "^6.0.0-next.8",

    "@types/bootstrap": "^5.1.9",
    "bootstrap": "^5.1.3",
```

After updating from 6.0.0-next.7 to 6.0.0-next.8, I have the following errors:

```
Error: node_modules/@ngx-formly/core/lib/models/fieldconfig.d.ts:38:13 - error TS2411: Property 'minlength' of type 'string | ((error: any, field: FormlyFieldConfig) => string | Observable<string>) | undefined' is not assignable to 'string' index type 'string | ((error: any, field: FormlyFieldConfig) => string | Observable<string>)'.

38             minlength?: ValidationMessageOption['message'];
               ~~~~~~~~~
```

```
Error: node_modules/@ngx-formly/core/lib/models/fieldconfig.d.ts:40:13 - error TS2411: Property 'maxlength' of type 'string | ((error: any, field: FormlyFieldConfig) => string | Observable<string>) | undefined' is not assignable to 'string' index type 'string | ((error: any, field: FormlyFieldConfig) => string | Observable<string>)'.

40             maxlength?: ValidationMessageOption['message'];
               ~~~~~~~~~
```

I need help.

Thank you,
Iulius Ciorica

**Comment by adora-tech** [comment]
My compiler reports:

![image](https://user-images.githubusercontent.com/58594685/155387252-78d2b8e7-1b0e-4591-8abf-02f3d664818d.png)

**Comment by aitboudad** [comment]
Could you please share your `tsconfig.json` as I unable to reproduce it on my side, Thanks!

**Comment by adora-tech** [comment]
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

Thank you,
Iulius

**Comment by adora-tech** [comment]
If I explicitly use the version below, the application compiles ok, again:

    "@ngx-formly/bootstrap": "6.0.0-next.7",
    "@ngx-formly/core": "6.0.0-next.7",
    "@ngx-formly/schematics": "6.0.0-next.7",

Thank you,
Iulius

**Comment by ogix** [comment]
I have the same problem

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-next.9](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.9) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
