### ISSUE TITLE
change one value in form based on another value in form similar to bug #1116

### ISSUE THREAD

**Issue by Nzkhan** [ngx-formly/ngx-formly#2165]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

change one value in form based on another value in form similar to bug [#1116](https://github.com/ngx-formly/ngx-formly/issues/1116)

from which I am referring this comment [here](https://github.com/ngx-formly/ngx-formly/issues/1116#issuecomment-412297872) by @aitboudad 

while the stackblitz example works fine with "@ngx-formly/core": "5.0.0-beta.1", but I am having issue in implementing the same in the latest version of "@ngx-formly/core": "^5.5.14"
NOTE: I want to achieve the same thing which is shown in the above example link. 

`
      "change": "this.addTotal.bind(this)"
`

I think the change event name has been changed in the later versions

which is giving me this error
```
core.js:5882 ERROR TypeError: this.to.change is not a function
    at FormlyAttributes.onChange (ngx-formly-core.js:1589)
    at FormlyAttributes_change_HostBindingHandler (ngx-formly-core.js:1643)
    at executeListenerWithErrorHandling (core.js:21708)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21750)
    at HTMLInputElement.<anonymous> (platform-browser.js:934)
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41255)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:481)
```

can someone please point me to the right direction.

> EDIT: I am using JSON-Powered Approch

**Comment by pascalbe-dev** [comment]
If I may try to help. 
Are you working with a JSON powered form? 
If yes, I do not think you can pass logic that way or even use change handlers, but I'm not sure.

If no, then you simply have to pass the change Handler as function and not as string (the error message shows, that the change handler does not have the correct type (should be a function). 

` 
templateOptions: {
  change: this.addTotal.bind(this)
}
`

**Comment by Nzkhan** [comment]
Yes @pascalbe-dev , I am using Json-Powered Form.
I was able to do this in the select control like this

> {
>     "key": "ds-sport",
>     "type": "select",
>     "templateOptions": {
>       "label": "Sport",
>       "options": [],
>       "changeExpr": "this.bindteams($event, field)",
>       "valueProp": "id",
>       "labelProp": "name"
>     }
>   }

and i have written my execution login in the corresponding component method with the name `this.bindteams($event, field)`

but I am not able to bind the change event for input control.
Anyways thanks @pascalbe-dev  for the answer, someone else may know the correct way to bind the on change event for input control.

**Comment by pascalbe-dev** [comment]
Okay. :D was worth a try. Good luck.

**Comment by Nzkhan** [comment]
Tried the below method and it worked for me,
> {
    "key": "total",
    "type": "input",
    "templateOptions": {
      "label": "Total",
      "description": "The total cost of all goods should automatically populate here.  That is, the price of good 1 plus the price of good 2."
    },
    **"expressionProperties": {
      "model.total" : "Number(model.price1) + Number(model.price2)"**
    }
  }

 using the **ExpressionProperties**

**Comment by mmahmutovic** [comment]
Neither do change or expressionProperties work on latest version.
I need changing one field based on other input as well. When I debug it, values are changed, but not shown on ui.

**Comment by nawazRazor** [comment]
> Neither do change or expressionProperties work on latest version.
> I need changing one field based on other input as well. When I debug it, values are changed, but not shown on ui.

Hi @mmahmutovic, I have tested the same thing with the latest version and it works fine.
could you share your fields json or fields array , may be we can have a solution then.

**Comment by mmahmutovic** [comment]
To have that change, I used keyup: () { // logic here }

**Comment by Ezhilisai** [comment]
templateOptions: {
     change: ($view) => {
          $view?.parent?.formControl?.controls?.fieldName.setValue('anything')
     }
}

This will work for sure.
